### PR TITLE
all: Represent GLsync as uintptr, not unsafe.Pointer.

### LINKED ISSUE #71: gl.FenceSync returns invalid unsafe.Pointer, causing crash
gl.FenceSync returns the created fence as an unsafe.Pointer. However, values returned by glFenceSync aren't necessarily valid pointers to memory owned by the driver.

On my system (nvidia 378.13 on Linux), for example, glFenceSync returns increasing numbers, starting at 1. The issue with that is that the Go runtime expects pointers in unsafe.Pointer to be valid, either pointing to memory owned by the Go memory allocator, or valid, non-Go memory. Pointers such as "1" are neither, which causes runtime.writebarrierptr to abort the program with a "bad pointer in write barrier" error. Similarly, the driver might return a value that looks like a valid pointer to Go memory, preventing said Go memory from being garbage collected as long as the unsafe.Pointer is alive.

To simulate the issue, compile https://play.golang.org/p/614oIx_Y1D and run it with GOGC=0 (to force frequent GCs, triggering the problem faster.). You should see the following:

```
$ GOGC=0 ./foo
runtime: writebarrierptr *0x4fa230 = 0x1
fatal error: bad pointer in write barrier

runtime stack:
runtime.throw(0x4a81ca, 0x1c)
	/usr/lib/go/src/runtime/panic.go:596 +0x95
runtime.writebarrierptr.func1()
	/usr/lib/go/src/runtime/mbarrier.go:208 +0xbd
runtime.systemstack(0x4fab00)
	/usr/lib/go/src/runtime/asm_amd64.s:327 +0x79
runtime.mstart()
	/usr/lib/go/src/runtime/proc.go:1132

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/lib/go/src/runtime/asm_amd64.s:281 fp=0xc420048f00 sp=0xc420048ef8
runtime.writebarrierptr(0x4fa230, 0x1)
	/usr/lib/go/src/runtime/mbarrier.go:209 +0x96 fp=0xc420048f38 sp=0xc420048f00
main.main()
	/tmp/foo.go:15 +0x9b fp=0xc420048f88 sp=0xc420048f38
runtime.main()
	/usr/lib/go/src/runtime/proc.go:185 +0x20a fp=0xc420048fe0 sp=0xc420048f88
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420048fe8 sp=0xc420048fe0
```

I would recommend returning a uintptr instead (and, similarly, accepting a uintptr in gl.ClientWaitSync and gl.WaitSync).

### PR DESCRIPTION
**Pull request by shurcooL**
Regenerate all bindings after generator change in go-gl/glow#79.

Done with latest version of glow:

	go generate -tags=gen github.com/go-gl/gl

Resolves #71.

/cc @errcw @dominikh

### CODE REVIEW

**Comment by errcw** [comment]
LGTM, should merge pending Travis build confirmation.

**Comment by shurcooL** [comment]
It fails to compile:

```
$ go test ./v4.5-core/gl
# github.com/go-gl/gl/v4.5-core/gl
v4.5-core/gl/package.go:5490: cannot convert sync (type uintptr) to type C.GLsync
v4.5-core/gl/package.go:5662: cannot convert ret (type C.GLsync) to type uintptr
v4.5-core/gl/package.go:5766: cannot convert sync (type uintptr) to type C.GLsync
v4.5-core/gl/package.go:5972: cannot convert ret (type C.GLsync) to type uintptr
v4.5-core/gl/package.go:6480: cannot convert sync (type uintptr) to type C.GLsync
v4.5-core/gl/package.go:6803: cannot convert sync (type uintptr) to type C.GLsync
v4.5-core/gl/package.go:8205: cannot convert sync (type uintptr) to type C.GLsync
```

**Comment by errcw** [comment]
Alas. Go is unhappy converting between `uintptr` and a C pointer type. Which is a little strange because we're already doing the same thing for `GLhandleARB` which maps to `void *` on Mac OS. Maybe `void*` is special compared to an anonymous struct pointer?

It _might_ be safe to do a just-in-time conversion from `uintptr` to `unsafe.Pointer` (but the GC may still catch this at exactly the wrong moment)? Alternatively we could change the C function signature and cast the value there, though that's not yet well supported by glow.

**Comment by errcw** [comment]
Dropping this PR given we implemented a slightly different fix in Glow.

**Pull request closed without merging**
